### ISSUE TITLE
Custom data

### ISSUE THREAD

**Issue by priya-kato** [manbomb/esp-idf-ble-provisioning-rn#5]
cannot write customdata to device

**Comment by manbomb** [comment]
Can you give me your code? Maybe the errors' traces.

**Comment by ReactRaylogic** [comment]
send custom data function of the demo code itself doesnot work.
gives error as 
`Possible Unhandled Promise Rejection (id: 1):
TypeError: undefined is not a function
TypeError: undefined is not a function
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:95447:86)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/13731o5t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/13731o5t/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:26200:26)
    at _callTimer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:26119:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:26149:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:26312:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:2407:46)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:2219:45)
    at __guard (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:2391:15)
    at flushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:2218:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.bleapp&modulesOnly=false&runModule=true:2212:33)`
